# Generated by Django 2.2.7 on 2020-04-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Application name')),
                ('api_key', models.CharField(max_length=256, unique=True, verbose_name='API Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is application active?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'unique_together': {('name', 'api_key')},
            },
        ),
    ]
